- name: create ec2 instances
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: provision instances
      ec2:
        key_name: ubuadmin
        group: web
        region: us-east-2
        instance_type: t2.micro
        image: ami-0552e3455b9bc8d50
        #exact_count: 1
        count_tag:
          Name: Web
        instance_tags:
          Name: web
          Type: autospin
          App: wordpress
      register: ec2

    # - name: Wait for SSH to come up
    #   delegate_to: "{{ item.private_dns_name }}"
    #   wait_for_connection:
    #     delay: 30
    #     timeout: 320
    #   with_items: "{{ ec2.instances }}"

    - pause:
        minutes: 1

    - name: create hostlist
      add_host:
        hostname: "{{ item.private_dns_name }}"
        groupname: ubulaunched
        ansible_ssh_user: ubuntu
      with_items: "{{ ec2.instances }}"

- name: install
  hosts: ubulaunched
  become: True
  gather_facts: false
  tasks:
  - Name: Install Python
    raw: sudo apt-get -y install python-minimal
  - Name: Install packages
    apt: 
      name: "{{ item }}"
      state: present

    with_items:
      - apache2
      - mysql-server
      - php7.2-mysql
      - php7.2
      - php7.2-gd
      - php7.2-ssh2
      - libapache2-mod-php7.2
      - python-mysqldb


- name: configure wordpress
  hosts: ubulaunched
  become: True
  gather_facts: false
  roles:
    - mysql
    - wordpress


    

        
