- name: Create Nginx container
  docker_container:
    user: root
    network_mode: host
    name: nginx
    image: nginx
    state: started
    pull: yes
    ports:
     - "{{ http_port }}:{{ http_port }}"
    
  
