---
- hosts: web # Host or Group of Selections
  become: true
  vars:
    httpd_port: 8080
  tasks:
  - name: copy
    copy: 
      src: ~/cloudready/devopstraining/ansible/roles/apache2/files/httpd.conf
      dest: /etc/httpd/conf/httpd.conf
  - name: Install httpd # Naming the task for debug purpose
    yum: name=httpd state=present  # Using module ( doing the task )
  - name: Start httpd
    service: name=httpd state=started enabled=yes


- hosts: db
  become: true
  tasks:
  - name: Install mysql
    yum: name=mysql state=present
