- rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

- get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- shell: sudo yum repolist

- yum:
    name: "{{ item }}"
    state: present
  with_items:
    - java-1.8.0-openjdk
    - jenkins