- apt:
    name: default-jdk
    update_cache: yes

- apt:
    name: systemd

- name: copy conf file
  copy:
    src: tomcat.service
    dest: /etc/systemd/system/tomcat.service


- name: add tomcat group
  shell: groupadd tomcat

- name: add user
  shell: useradd -s /bin/false -g tomcat -d /opt/tomcat tomcat

- name: download requirements
  get_url:
    url: http://mirror.cogentco.com/pub/apache/tomcat/tomcat-8/v8.5.33/bin/apache-tomcat-8.5.33.tar.gz
    dest: /tmp/apache-tomcat-8.5.33.tar.gz

- name: copy script
  copy: 
    src: tomcat.sh
    dest: tomcat.sh

- name: execute install script
  command: sudo sh /home/ubuntu/tomcat.sh

